name: Main

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
      - '!develop'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter pub global activate melos
      - run: |
          melos bootstrap
          melos run build:android

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter pub global activate melos
      - run: |
          melos bootstrap
          melos run build:ios
  
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter pub global activate melos
      - run: |
          melos bootstrap
          melos run build:windows

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter pub global activate melos
      - run: |
          melos bootstrap
          melos run build:macos

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - run: flutter pub global activate melos
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: |
          melos bootstrap
          melos run build:linux